config/routes.rb
Zakaztaxi::Application.routes.draw do
  get "refreshdata/index"

  get "refreshdata/refresh"

  get "taxist/index"

  get "taxist/vote"

  get "taxist/list"

 match '/zakazs/mainpanel'=>'zakazs#mainpanel'
 match '/login'=>'login#login'
 match '/register'=>'register#index'

  resources :zakazs
  get  "zakazs/index"
  get  "zakazs/mainpanel"
  post "zakazs/mainpanel"

  get  "register/index"
  post "register/index"
  get  "register/registred"

  get  "login/index"
  get  "login/login"
  post "login/login"
  get  "login/logout"
  

end

app/models/zakaz.rb
class Zakaz < ActiveRecord::Base
end

app/controllers/zakazs_controller.rb
class ZakazsController < ApplicationController
  # GET /zakazs
  # GET /zakazs.xml
  def index
    user_id= session[:user_id]
    #    @zakazs= Zakaz.where(:disp_id=>user_id.to_s, :status=>'0').all

    #@zakazs = Zakaz.all
    @zakazs = Zakaz.find(:all, :conditions=>"disp_id="+user_id.to_s)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @zakazs }
      format.json  { render :json => @zakazs }
      
    end
  end

  # GET /zakazs/1
  # GET /zakazs/1.xml
  def show
    @zakaz = Zakaz.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @zakaz }
    end
  end

  # GET /zakazs/new
  # GET /zakazs/new.xml
  def new
    @zakaz = Zakaz.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @zakaz }
    end
  end

  # GET /zakazs/1/edit
  def edit
    @zakaz = Zakaz.find(params[:id])
  end

  # POST /zakazs
  # POST /zakazs.xml
  def create

    @zakaz = Zakaz.new(params[:zakaz])
    @zakaz.disp_id= session[:user_id]
    @zakaz.status='0'

    respond_to do |format|
      if @zakaz.save
        format.html { redirect_to(:action =>:mainpanel) }
        format.xml  { render :xml => @zakaz, :status => :created, :location => @zakaz }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @zakaz.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /zakazs/1
  # PUT /zakazs/1.xml
  def update
    @zakaz = Zakaz.find(params[:id])
#    redirect_to( :action =>:mainpanel)
    respond_to do |format|
      if @zakaz.update_attributes(params[:zakaz])
#        # format.html { redirect_to(@zakaz, :notice => 'Zakaz was successfully updated.') }
        format.html { redirect_to( :action =>:mainpanel) }
#        format.xml  { head :ok }
#      else
#        format.html { render :action => "edit" }
#        format.xml  { render :xml => @zakaz.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /zakazs/1
  # DELETE /zakazs/1.xml
  def destroy
    @zakaz = Zakaz.find(params[:id])
    @zakaz.destroy

    respond_to do |format|
      format.html { redirect_to(zakazs_url) }
      format.xml  { head :ok }
    end
  end

  def mainpanel
    user_id= session[:user_id]
    
    @zakaz = Zakaz.new
#    @zakazs = Zakaz.find(:all, :conditions=>"disp_id="+user_id.to_s)
    @zakazs= Zakaz.where(:disp_id=>user_id.to_s, :status=>'0')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @zakazs }
      format.json  { render :json => @zakazs }
    end
  end

end

app/helpers/zakazs_helper.rb
module ZakazsHelper
end

app/views/zakazs/_form.html.erb
<%= form_for(@zakaz) do |f| %>
  <% if @zakaz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zakaz.errors.count, "error") %> prohibited this zakaz from being saved:</h2>

      <ul>
      <% @zakaz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :disp_id %><br />
    <%= f.text_field :disp_id %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :useradress %><br />
    <%= f.text_field :useradress %>
  </div>
  <div class="field">
    <%= f.label :createdate %><br />
    <%= f.datetime_select :createdate %>
  </div>
  <div class="field">
    <%= f.label :maxtime %><br />
    <%= f.text_field :maxtime %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :taxist_id %><br />
    <%= f.text_field :taxist_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zakazs/_small_form.htm.erb
<%= form_for(@zakaz) do |f| %>
  <% if @zakaz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zakaz.errors.count, "error") %> prohibited this zakaz from being saved:</h2>

      <ul>
      <% @zakaz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :useradress %><br />
    <%= f.text_field :useradress %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zakazs/edit.html.erb
<h1>Editing zakaz</h1>

<%= render 'form' %>

<%= link_to 'Show', @zakaz %> |
<%= link_to 'Back', zakazs_path %>

app/views/zakazs/index.html.erb
<h1>Listing zakazs</h1>
user <%=session[:user_id]%>
<table>
  <tr>
    <th>Disp</th>
    <th>Phone</th>
    <th>Useradress</th>
    <th>Createdate</th>
    <th>Maxtime</th>
    <th>Status</th>
    <th>Taxist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zakazs.each do |zakaz| %>
  <tr>
    <td><%= zakaz.disp_id %></td>
    <td><%= zakaz.phone %></td>
    <td><%= zakaz.useradress %></td>
    <td><%= zakaz.createdate %></td>
    <td><%= zakaz.maxtime %></td>
    <td><%= zakaz.status %></td>
    <td><%= zakaz.taxist_id %></td>
    <td><%= link_to 'Show', :controller=>:zakazs, :method => :edit%></td>
    <td></td>
    <td><%= link_to 'Destroy', :confirm => 'Are you sure?',:controller=>:zakazs, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zakaz', :controller=>:zakazs, :action => :new%>

app/views/zakazs/mainpanel.html.erb
user <%=session[:user_id]%>
<hr>


<table border="1">
  <tr>
    <td>
      acive zakaz
      <table>
        <tr>
          <th>adress</th>
        </tr>

        <% @zakazs.each do |zakaz| %>
          <tr>
            <td><%= zakaz.useradress %></td>
          </tr>
        <% end %>
      </table>
    </td>
    <td>
      new zakaz
      <%= form_for(@zakaz) do |f| %>
  <% if @zakaz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zakaz.errors.count, "error") %> prohibited this zakaz from being saved:</h2>

      <ul>
      <% @zakaz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :useradress %><br />
    <%= f.text_field :useradress %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    </td>
  </tr>



</table>

app/views/zakazs/new.html.erb
<h1>New zakaz</h1>

<%= render 'form' %>

<%= link_to 'Back', zakazs_path %>

app/views/zakazs/show.html.erb
<p id="notice"><%= notice %></p>
<%=zakazs_path %>
<p>
  <b>Disp:</b>
  <%= @zakaz.disp_id %>
</p>

<p>
  <b>Phone:</b>
  <%= @zakaz.phone %>
</p>

<p>
  <b>Useradress:</b>
  <%= @zakaz.useradress %>
</p>

<p>
  <b>Createdate:</b>
  <%= @zakaz.createdate %>
</p>

<p>
  <b>Maxtime:</b>
  <%= @zakaz.maxtime %>
</p>

<p>
  <b>Status:</b>
  <%= @zakaz.status %>
</p>

<p>
  <b>Taxist:</b>
  <%= @zakaz.taxist_id %>
</p>


<%= link_to 'Edit', edit_zakaz_path(@zakaz) %> |
<%= link_to 'Back', zakazs_path %>